-- Owner : SAGAR R INGALE--
-- DATE	 : 14-12-2019--
--Schema : HEALTH and INSURANCE--

/* Action
1. Need to change UserName from TABLE
*/

--TABLES--

--ADDRESS
--BILLING
--CITY
--CLAIM
--COUNTRY
--DEPARTMENT
--DISEASE
--DOCTOR
--E_ADDRESS
--FAMILY_DETAIL
--HOSPITAL
--PAIIENT
--POLICY
--STAFF
--STATE
--TEST

-----------TABLE CREATION----------
CREATE TABLE ADDRESS
  (
    P_ADD CHARACTER VARYING(10) PRIMARY KEY,
    AREA  CHARACTER VARYING(50) ,
    PIN   INTEGER ,
    CT_ID CHARACTER VARYING(10)
  );

CREATE TABLE BILLING
  (
    BILL_ID   CHARACTER VARYING(20) PRIMARY KEY,
    BILL_AMT  CHARACTER VARYING(20) ,
    ADD_DATE  DATE ,
    DESR_DATE DATE
  );
  
CREATE  TABLE CITY
  (
    CT_ID   CHARACTER VARYING(10) PRIMARY KEY,
    CT_NAME CHARACTER VARYING(20) ,
    ST_ID   CHARACTER VARYING(10)
  );

CREATE  TABLE CLAIM
  (
    CLAIM_ID   INTEGER PRIMARY KEY,
    STATUS     CHARACTER VARYING(20) ,
    ISSUE_DATE DATE ,
    ISSUE_AMT  INTEGER ,
    HOS_ID     CHARACTER VARYING(20) ,
    DOCT_ID    INTEGER ,
    DES_ID     CHARACTER VARYING(20) ,
    CL_DN_DT   DATE ,
    BILL_ID    CHARACTER VARYING(20),
	SYS_UPD_DATE TIMESTAMP 
  );

CREATE  TABLE COUNTRY
  (
    CON_ID   INTEGER PRIMARY KEY,
    CON_NAME CHARACTER VARYING(40)
  );
  
CREATE  TABLE DEPARTMENT
  (
    D_ID   CHARACTER VARYING(20) PRIMARY KEY,
    D_NAME CHARACTER VARYING(20) ,
    P_ADD  CHARACTER VARYING(10)
  );

CREATE  TABLE DISEASE
  (
    DES_ID   CHARACTER VARYING(20) PRIMARY KEY,
    DES_NAME CHARACTER VARYING(20) ,
    TEST_ID  CHARACTER VARYING(20)
  );

CREATE  TABLE DOCTOR
  (
    DOCT_ID    INTEGER PRIMARY KEY,
    D_NAME     CHARACTER VARYING(20) ,
    SPECIALIST CHARACTER VARYING(20) ,
    MOBILE     INTEGER,
    EXP        INTEGER ,
    P_ADD      CHARACTER VARYING(10) ,
    E_ADD      CHARACTER VARYING(10)
  );

CREATE  TABLE E_ADDRESS
  (
    E_ADD CHARACTER VARYING(10) PRIMARY KEY,
    DES   CHARACTER VARYING(30)
  );

CREATE  TABLE FAMILY_DETAIL
  (
    PID     INTEGER PRIMARY KEY,
    FAM_MEM INTEGER ,
    DETAIL  CHARACTER VARYING(100)
  );

CREATE  TABLE HOSPITAL
  (
    HOS_ID       CHARACTER VARYING(20) PRIMARY KEY,
    HOS_NAME     CHARACTER VARYING(20) ,
    P_ADD        CHARACTER VARYING(10) ,
    IS_NETWORKED CHARACTER VARYING(20)
  );

CREATE  TABLE PAIIENT
  (
    PID          INTEGER PRIMARY KEY,
    F_NAME       CHARACTER VARYING(20) ,
    L_NAME       CHARACTER VARYING(20) ,
    B_DATE       DATE ,
    PHONE        INTEGER,
    AADHAR       INTEGER,
    SYS_CRE_DATE TIMESTAMP NOT NULL ,
    SYS_UPD_DATE TIMESTAMP ,
    SEX          CHAR (1) ,
    P_ADD        CHARACTER VARYING(10) ,
    E_ADD        CHARACTER VARYING(10) ,
    BL_GR        CHARACTER VARYING(20) ,
    POL_NO       INTEGER ,
    CLAIM_ID     INTEGER ,
	POL_TYPE_ID   INTEGER,
	MED_HIST  CHARACTER VARYING(500) 
  );

CREATE  TABLE POLICY
  (
    POL_TYPE_ID   INTEGER PRIMARY KEY,
    POL_TYPE CHARACTER VARYING(20) ,
    TENURE   INTEGER ,
    BENIFIT  CHARACTER VARYING(200) ,
    PREMIUM  INTEGER
  );

CREATE  TABLE STAFF
  (
    EMP_ID       INTEGER PRIMARY KEY,
    F_NAME       CHARACTER VARYING(20) ,
    L_NAME       CHARACTER VARYING(20) ,
    B_DATE       DATE ,
    PHONE        INTEGER,
    AADHAR       INTEGER,
    JOIN_DATE    DATE ,
    SYS_CRE_DATE TIMESTAMP NOT NULL ,
    SYS_UPD_DATE TIMESTAMP ,
    SEX          CHAR (1) ,
    P_ADD        CHARACTER VARYING(10) ,
    E_ADD        CHARACTER VARYING(10) ,
    BL_GR        CHARACTER VARYING(20) ,
    POL_NO       INTEGER ,
    D_ID         CHARACTER VARYING(20) ,
    CLAIM_ID     INTEGER,
	POL_TYPE_ID  INTEGER,
	MED_HIST    CHARACTER VARYING(500)
  );

CREATE  TABLE STATE
  (
    ST_ID   CHARACTER VARYING(10) PRIMARY KEY,
    ST_NAME CHARACTER VARYING(40) ,
    CON_ID  INTEGER NOT NULL
  );
 
CREATE  TABLE TEST
  (
    TEST_ID   CHARACTER VARYING(20) PRIMARY KEY,
    TEST_NAME CHARACTER VARYING(20) ,
    PRICE     INTEGER
  );

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            16
-- CREATE INDEX                            16
-- ALTER TABLE                             38
